// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderCustomer struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Orderin     pgtype.Date
	Orderdue    pgtype.Date
	Rushed      pgtype.Bool
	Form        pgtype.Text
	Visible     pgtype.Int4
	Email       pgtype.Text
	Phone       pgtype.Text
	Completed   pgtype.Bool
	Removed     pgtype.Bool
	Completedat pgtype.Date
}

type OrderSchemaMigration struct {
	Version int64
	Dirty   bool
}

type OrderSession struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type OrderUser struct {
	ID             int32
	Email          string
	HashedPassword string
	Created        pgtype.Timestamp
	Authkey        string
	Authkeyexpires pgtype.Timestamp
	Authenticated  bool
}
