// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const testing = `-- name: Testing :one
select id
from users
where id = $1
`

func (q *Queries) Testing(ctx context.Context, dollar_1 pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, testing, dollar_1)
	var id int32
	err := row.Scan(&id)
	return id, err
}
